# Site settings
title: Jianchao Li
email: 
description: "I love writing deep learning codes for computer vision."
baseurl: ""
url: "http://jianchao-li.github.io"
github_username:  jianchao-li
linkedin_username: jianchao-li
twitter_username: jianchao2017
facebook_username: jianchao.li.fighter


# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
