# Site settings
title: Jianchao Li blog
email: 
description: "I love writing deep learning codes for computer vision."
baseurl: ""
url: "http://jianchao-li.github.io"
twitter_username: jianchao2017
github_username:  jianchao-li

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
